name: CI - Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  PYTHONUTF8: 1

jobs:
  unit_test:
    name: Test
    strategy:
      matrix:
        python-version: [3.9, 3.13]
        os: [ubuntu-22.04, windows-2022, macos-14]
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME_TAG: ci_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Python Poetry
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: 1.4.2
      
      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true
      
      - name: Print Python environment information
        run: |
          poetry env info
          poetry --version
          poetry run pip -V
      
      - name: Install dependencies
        run: |
          poetry install --all-extras
      
      - name: Linting
        run: |
          poetry run flake8 . --exclude .venv,examples,tests --count --show-source --statistics
      
      - name: Check Format
        run: |
          poetry run black --check --diff --color agentic_doc/
      
      - name: Type Checking
        run: |
          poetry run mypy agentic_doc
      
      - name: Test with pytest
        run: |
          poetry run pytest -s -vvv tests/unit
